### ISSUE TITLE
Translate www.kiwix.org in Spanish

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#159]
Visitor browser language second position is Spanish. See https://stats.kiwix.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=5#?idSite=5&period=day&date=yesterday&category=General_Visitors&subcategory=UserCountry_SubmenuLocations

We should probably translate our Website in Spanish.

**Comment by kelson42** [comment]
@Popolechien Could you please organize this with Luis https://toot.community/@ark74/110124898155528831 who is a long term supporter and user of Kiwix?

**Comment by kelson42** [comment]
Actually checking again the stats, and we have slightly more people visiting www.kiwix.org from Spanish speaking countries than from China mainland

**Comment by Ark74** [comment]
Glad to help, let me know when you are ready. 👍

**Comment by Popolechien** [comment]
@Ark74 Will do, thanks. There's a bunch of changes on the way so we'll ping you when things stabilize. In the meantime, can you please send a quick note to hello@kiwix.org so we send you an invite to our WordPress?

**Comment by Ark74** [comment]
Done, thanks.

**Comment by kelson42** [comment]
@Popolechien Thx, please let us know about the blockers (maybe they have to be tracked here with tickets).

**Comment by kelson42** [comment]
It seems so far only a few pages have been translated. Important one like https://www.kiwix.org/en/download/ are still not.

**Comment by Ark74** [comment]
Sorry, I've been a bit short in time, I'll work on that this weekend.

**Comment by Ark74** [comment]
The task available are complete, maybe you might like to add more?

**Comment by Popolechien** [comment]
I've sent a few more - some of them might look strange as they're structural pages (e.g. "gallery"). Thanks a lot!

**Comment by Ark74** [comment]
Alright!
Will be taking care of them one step at the time.

Cheers! :+1:
