### ISSUE TITLE
kiwix.org download page doe not provide macOS .dmg link

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#227]
See
![image](https://github.com/kiwix/web/assets/1029718/3649899d-b7ea-45b0-aeab-25aa98d509ed)

A new button should be added at the right of the app store button:
* label: macOS Disk Image
* link: https://download.kiwix.org/release/kiwix-desktop-macos/kiwix-desktop-macos.dmg

Blocked by https://github.com/kiwix/kiwix-apple/issues/760

**Comment by Popolechien** [comment]
Done.

**Comment by kelson42** [comment]
I still don't see it
![image](https://github.com/user-attachments/assets/158a3016-dff5-474c-86a8-5bd8e5d755a1)

**Comment by Popolechien** [comment]
The changes appear on the page for people that are logged in onto the website, but need to be saved both in the `applications` subset and page to appear to normal users. Should work now.
