### ISSUE TITLE
Sentence "This version is compatible with all Apple device" is wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/web#228]
At https://kiwix.org/en/applications/
![image](https://github.com/kiwix/web/assets/1029718/6c1df597-4655-49a1-b5df-e19e1ec45b8b)

This is false, we support only a 3 latest versions of both macOS and iOS, see [reference](https://github.com/kiwix/kiwix-apple).

> Most recent versions of Kiwix support the three latest major versions of the OSes (either iOS or macOS). Older versions of Kiwix being still downloadable for older versions of macOS and iOS on the Mac App Store.

I propose to write: "Latest release designed for iOS 15-16-17 & macOS 12-13-14 (previous releases still available in App Store and in [macOS DMG format](https://download.kiwix.org/release/kiwix-desktop-macos/)." [I have updated the release check-list according to secure this is updated properly](https://github.com/kiwix/kiwix-apple/issues/645).

Blocked by https://github.com/kiwix/kiwix-apple/issues/760

**Comment by rgaudin** [comment]
To me 760 on apple is for next release ; so not a blocker here

**Comment by kelson42** [comment]
Would just try to avoid fixing things and having to update then again the links.

**Comment by rgaudin** [comment]
So should we rename 3.3.0 already?

**Comment by rgaudin** [comment]
Renamed ; FYI dmg permalink is https://download.kiwix.org/release/kiwix-desktop-macos/kiwix-macos.dmg

**Comment by kelson42** [comment]
> Renamed ; FYI dmg permalink is https://download.kiwix.org/release/kiwix-desktop-macos/kiwix-macos.dmg

I don't understand why the directoty has not been renamed too!?

**Comment by rgaudin** [comment]
> I don't understand why the directory has not been renamed too!?

Has someone asked for it or even mentioned it?

**Comment by rgaudin** [comment]
Done ; new permalink: https://download.kiwix.org/release/kiwix-macos/kiwix-macos.dmg

**Comment by Popolechien** [comment]
I've put something a little more generic "_This version is compatible with all devices currently supported by Apple (usually the last 3 OS updates)._"

**Comment by kelson42** [comment]
> I've put something a little more generic "_This version is compatible with all devices currently supported by Apple (usually the last 3 OS updates)._"

The phrasing is AFAIK still incorrect, Apple supports more than 3 latest version. In addition, inTunes provides older versions of Kiwix for older version of the OS.

I propose following phrase: "We actively develop and maintain Kiwix for the 3 most recent major versions of iOS and macOS."

**Comment by Popolechien** [comment]
Fixed.
